// Shared types — single source of truth (ARCHITECTURE.md §5).
// Imported by both the client and the server.

export type Tier = 'safe' | 'real' | 'raw';
export type Category = 'love' | 'identity' | 'fitness' | 'earnings';

export type LinkKind =
  | 'refines'      // target is a deeper cut of source. The descent spine.
  | 'assumes'      // source only holds if target is true. The interrogation edge.
  | 'contradicts'  // target undercuts source. How assumptions die.
  | 'evidence';    // target is a lyric/moment supporting source.

export type Origin = 'user' | 'ai';
export type Status = 'committed' | 'proposed';

export interface Bubble {
  id: string;                 // nanoid
  kind: 'idea' | 'lyric';     // 'lyric' lives in the outer margin, has no tier
  tier: Tier | null;          // null only when kind === 'lyric'
  category: Category | null;  // null only when kind === 'lyric'
  label: string;              // ≤ 12 words. Renders in the bubble.
  sourceLine: string;         // verbatim lyric fragment the bubble derives from (D23).
                              // Server-validated against doc.source; fabrication guard.
                              // For kind 'lyric' it is the line itself.
  note?: string;              // longer expansion, shown in Inspector.
  exhausted?: boolean;        // D35: asked to go deeper and declined. Set by the
                              // client when a descend returns nothing. Optional;
                              // pre-D35 files backfill undefined. No migration.
  citationUnverified?: boolean; // D39: sourceLine didn't match doc.source. The
                              // reading stays — provenance is unverified, and
                              // renders with a quiet visible marker. Optional.
  move?: string;              // D58, RAW bubbles only: one sentence naming what
                              // the WRITER DID — a technique, never an effect on
                              // the listener. Generated by descend with the full
                              // descent in context; absent = no move found (the
                              // honest no) or a pre-D58 file. EXPERIMENTAL —
                              // killable by deleting this field, its suffix
                              // clause, and the Readings foot together.
  position: { x: number; y: number };
  origin: Origin;
  status: Status;
  createdAt: string;          // ISO
}

export interface Link {
  id: string;
  source: string;             // Bubble.id
  target: string;             // Bubble.id
  kind: LinkKind;
  rationale?: string;         // one-sentence "why". Shown in Inspector.
  origin: Origin;
  status: Status;
}

// D46 — Descent and Return: one chosen descent rewritten as a narrative
// arc of five beats, RAW → REAL → SAFE → REAL → RAW. The beat boundaries
// exist for the display (the dive-profile index, the type crescendo, the
// roman numerals); the prose itself is one continuous piece — the
// transitions are the whole claim.
export interface ArcBeat {
  tier: Tier;                 // fixed by position: raw, real, safe, real, raw
  text: string;               // this beat's passage
}

export interface Arc {
  id: string;                 // nanoid
  rawId: string;              // the RAW bubble the arc was built from
  beats: ArcBeat[];           // exactly five
  createdAt: string;          // ISO
}

export interface BubbleMapDoc {
  version: 2;
  id: string;
  title: string;              // e.g. "Mr. Brightside — The Killers"
  subject: 'song' | 'self';   // v1 always 'song'; swaps the prompt variant
  source?: string;            // free text: lyrics, notes, your analysis
  bubbles: Bubble[];
  links: Link[];
  rejected: Bubble[];         // unpicked candidates: persisted, never rendered (D24).
  // D48: `keeperId` and `nominatedIds` are CUT — the keeper asked for a
  // declared preference; the arc IS the choosing act (judgment happens
  // when it produces something). Pre-D48 files still carry both fields
  // on disk, deliberately: unread, unmigrated, unstripped, so a future
  // session can see what was there.
  arcs?: Arc[];               // D46: descent-and-return arcs, persisted — each
                              // costs an AI call and is the most expensive
                              // artifact the tool makes; losing one on reload
                              // would be the worst small failure available.
                              // Optional, backfills undefined, no migration.
  createdAt: string;
  updatedAt: string;
}
